<?php

use Illuminate\Database\Seeder;
use App\Geo;

class GeosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Geo::class, 10)->create()->each(function($city){
        // 	$city->municipalities()->saveMany(
        //         factory(Geo::class, rand(1, 5))->make()
        //     );
        // });

        DB::table('geos')->insert([

            ['name' => 'Ada'],
            ['name' => 'Aleksandrovac'],
            ['name' => 'Alibunar'],
            ['name' => 'Aleksinac'],
            ['name' => 'Apatin'],
            ['name' => 'Aranđelovac'],
            ['name' => 'Arilje'],
            ['name' => 'Azanja'],
            ['name' => 'Babušnica'],
            ['name' => 'Bač'],
            ['name' => 'Bačka Palanka'],
            ['name' => 'Bačka Topola'],
            ['name' => 'Bački Petrovac'],
            ['name' => 'Bačko Petrovo Selo'],
            ['name' => 'Bajina Bašta'],
            ['name' => 'Banatski Karlovac'],
            ['name' => 'Banatsko Novo Selo'],
            ['name' => 'Banja Koviljača'],
            ['name' => 'Barajevo'],
            ['name' => 'Batajnica'],
            ['name' => 'Batočina'],
            ['name' => 'Bečej'],
            ['name' => 'Bela Crkva'],
            ['name' => 'Bela Palanka'],
            ['name' => 'Beočin'],
            ['name' => 'Beograd'],
            ['name' => 'Beška'],
            ['name' => 'Blace'],
            ['name' => 'Bogatić'],
            ['name' => 'Bojnik'],
            ['name' => 'Boljevac'],
            ['name' => 'Bor'],
            ['name' => 'Borča'],
            ['name' => 'Bosilegrad'],
            ['name' => 'Brus'],
            ['name' => 'Bujanovac'],
            ['name' => 'Crvenka'],
            ['name' => 'Čačak'],
            ['name' => 'Čelarevo'],
            ['name' => 'Čoka'],
            ['name' => 'Čurug'],
            ['name' => 'Ćićevac'],
            ['name' => 'Ćuprija'],
            ['name' => 'Despotovac'],
            ['name' => 'Dimitrovgrad'],
            ['name' => 'Doljevac'],
            ['name' => 'Feketić'],
            ['name' => 'Futog'],
            ['name' => 'Gornji Milanovac'],
            ['name' => 'Horgoš'],
            ['name' => 'Inđija'],
            ['name' => 'Inostranstvo'],
            ['name' => 'Irig'],
            ['name' => 'Ivanjica'],
            ['name' => 'Jagodina'],
            ['name' => 'Kačarevo'],
            ['name' => 'Kać'],
            ['name' => 'Kanjiža'],
            ['name' => 'Kikinda'],
            ['name' => 'Kladovo'],
            ['name' => 'Knić'],
            ['name' => 'Knjaževac'],
            ['name' => 'Koceljeva'],
            ['name' => 'Kopaonik'],
            ['name' => 'Kosjerić'],
            ['name' => 'Kosovska Mitrovica'],
            ['name' => 'Kostolac'],
            ['name' => 'Kovačica'],
            ['name' => 'Kovilj'],
            ['name' => 'Kovin'],
            ['name' => 'Kragujevac'],
            ['name' => 'Kraljevo'],
            ['name' => 'Krupanj'],
            ['name' => 'Kruševac'],
            ['name' => 'Kučevo'],
            ['name' => 'Kula'],
            ['name' => 'Kuršumlija'],
            ['name' => 'Kusadak'],
            ['name' => 'Lajkovac'],
            ['name' => 'Lapovo'],
            ['name' => 'Lazarevac'],
            ['name' => 'Lebane'],
            ['name' => 'Leposavić'],
            ['name' => 'Leskovac'],
            ['name' => 'Loznica'],
            ['name' => 'Lučani'],
            ['name' => 'Ljig'],
            ['name' => 'Ljubovija'],
            ['name' => 'Majdanpek'],
            ['name' => 'Mali Iđoš'],
            ['name' => 'Mali Zvornik'],
            ['name' => 'Medveđa'],
            ['name' => 'Melenci'],
            ['name' => 'Merošina'],
            ['name' => 'Mionica'],
            ['name' => 'Mladenovac'],
            ['name' => 'Mol'],
            ['name' => 'Negotin'],
            ['name' => 'Niš'],
            ['name' => 'Nova Pazova'],
            ['name' => 'Nova Varoš'],
            ['name' => 'Novi Banovci'],
            ['name' => 'Novi Bečej'],
            ['name' => 'Novi Kneževac'],
            ['name' => 'Novi Pazar'],
            ['name' => 'Novi Sad'],
            ['name' => 'Obrenovac'],
            ['name' => 'Odžaci'],
            ['name' => 'Omoljica'],
            ['name' => 'Opovo'],
            ['name' => 'Palić'],
            ['name' => 'Pančevo'],
            ['name' => 'Paraćin'],
            ['name' => 'Petrovac na Mlavi'],
            ['name' => 'Petrovaradin'],
            ['name' => 'Pirot'],
            ['name' => 'Plandište'],
            ['name' => 'Pojate'],
            ['name' => 'Požarevac'],
            ['name' => 'Požega'],
            ['name' => 'Preševo'],
            ['name' => 'Priboj'],
            ['name' => 'Prijepolje'],
            ['name' => 'Prokuplje'],
            ['name' => 'Pukovac'],
            ['name' => 'Rača Kragujevačka'],
            ['name' => 'Raška'],
            ['name' => 'Ražanj'],
            ['name' => 'Ruma'],
            ['name' => 'Rumenka'],
            ['name' => 'Ruski Krstur'],
            ['name' => 'Senta'],
            ['name' => 'Sevojno'],
            ['name' => 'Sivac'],
            ['name' => 'Sjenica'],
            ['name' => 'Smederevo'],
            ['name' => 'Smederevska Palanka'],
            ['name' => 'Sokobanja'],
            ['name' => 'Sombor'],
            ['name' => 'Sopot'],
            ['name' => 'Srbobran'],
            ['name' => 'Sremska Kamenica'],
            ['name' => 'Sremska Mitrovica'],
            ['name' => 'Sremski Karlovci'],
            ['name' => 'Stara Pazova'],
            ['name' => 'Starčevo'],
            ['name' => 'Stari Banovci'],
            ['name' => 'Subotica'],
            ['name' => 'Surdulica'],
            ['name' => 'Svilajnac'],
            ['name' => 'Svrljig'],
            ['name' => 'Šabac'],
            ['name' => 'Šid'],
            ['name' => 'Štrpce'],
            ['name' => 'Temerin'],
            ['name' => 'Titel'],
            ['name' => 'Topola'],
            ['name' => 'Trstenik'],
            ['name' => 'Tutin'],
            ['name' => 'Ub'],
            ['name' => 'Užice'],
            ['name' => 'Valjevo'],
            ['name' => 'Varvarin'],
            ['name' => 'Velika Plana'],
            ['name' => 'Veliko Gradište'],
            ['name' => 'Veternik'],
            ['name' => 'Vinča'],
            ['name' => 'Vladičin Han'],
            ['name' => 'Vladimirci'],
            ['name' => 'Vlasotince'],
            ['name' => 'Vojka'],
            ['name' => 'Vranje'],
            ['name' => 'Vranjska Banja'],
            ['name' => 'Vrbas'],
            ['name' => 'Vrnjačka Banja'],
            ['name' => 'Vršac'],
            ['name' => 'Zaječar'],
            ['name' => 'Zlatibor'],
            ['name' => 'Zrenjanin'],
            ['name' => 'Zubin Potok'],
            ['name' => 'Zvečan'],
            ['name' => 'Žabalj'],
            ['name' => 'Žagubica'],
            ['name' => 'Žitorađa'],
        ]);
    }
}
